### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by ozette** [grmble/node-dicom#11]
The [minimal javascript demo](https://www.npmjs.com/package/dicom) at the bottom of that page results in the following error message:

```
/home/ozette/node-dicom-test/IM-0001-0004.dcm
{"name":"decoder","hostname":"NAS","pid":21194,"level":50,"error":{},"msg":"_action_wrapper:  emitting error","time":"2016-05-17T12:47:52.321Z","v":0}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: VR::consume_and_emit is not prepared to handle UNDEFINED_LENGTH
    at DicomError.Error (native)
    at new DicomError (/home/ozette/node-dicom-test/node_modules/dicom/lib/vrs.js:17:47)
    at OW.VR._consume_and_emit_known_value_length (/home/ozette/node-dicom-test/node_modules/dicom/lib/vrs.js:603:15)
    at OW.VR.consume_and_emit (/home/ozette/node-dicom-test/node_modules/dicom/lib/vrs.js:597:19)
    at Decoder._handle_element (/home/ozette/node-dicom-test/node_modules/dicom/lib/decoder.js:286:17)
    at Decoder._decode_dataelement (/home/ozette/node-dicom-test/node_modules/dicom/lib/decoder.js:198:23)
    at Decoder._decode_dataelement (/home/ozette/node-dicom-test/node_modules/dicom/lib/decoder.js:4:61)
    at Decoder._decode_dataset (/home/ozette/node-dicom-test/node_modules/dicom/lib/decoder.js:168:14)
    at Decoder.<anonymous> (/home/ozette/node-dicom-test/node_modules/dicom/lib/decoder.js:4:61)
    at Decoder._decode_metainfo (/home/ozette/node-dicom-test/node_modules/dicom/lib/decoder.js:163:19)
```

command:
`node test.js IM-0001-0004.dcm`

Do you mind to elaborate, which event is not error-handled?
What's missing in the example?

**Comment by ozette** [comment]
Would this package work with the latest stable node, v6.1.0?

**Comment by ozette** [comment]
I recommend this parser instead:
https://github.com/chafey/dicomParser

**Comment by grmble** [comment]
The error messages means that your input contains a dicom element of VR OW with undefined value length.

The parser only handles undefined value lengths for the VRs SQ, UN and OB.
