### ISSUE TITLE
dicom fails to parse headers due to "Unknown VR: US or SS"

### ISSUE THREAD

**Issue by soichih** [grmble/node-dicom#6]
Hello. Thank you for publishing this module. I am evaluating it to see if we can use it for one of our application. 

I have a sample DICOM image that I can view using a tool like RadiAnt DICOM Viewer. 
> https://dl.dropboxusercontent.com/u/3209692/1.3.12.2.1107.5.1.4.11035.30000013071013304456600000757.dcm

When I try to parse the header with node-dicom, I get an error message like following.

{"name":"decoder","hostname":"portal-dev1.odi.iu.edu","pid":10845,"level":50,"error":{},"msg":"_action_wrapper:  emitting error","time":"2015-02-15T19:34:07.722Z","v":0}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Unknown VR: US or SS
    at DicomError.Error (<anonymous>)
    at new DicomError (/home/hayashis/git/dicom/node_modules/dicom/lib/vrs.js:17:47)
    at Object.for_name (/home/hayashis/git/dicom/node_modules/dicom/lib/vrs.js:1369:13)
    at Decoder._handle_element (/home/hayashis/git/dicom/node_modules/dicom/lib/decoder.js:285:16)
    at Decoder._decode_dataelement (/home/hayashis/git/dicom/node_modules/dicom/lib/decoder.js:198:23)
    at Decoder._decode_dataelement (/home/hayashis/git/dicom/node_modules/dicom/lib/decoder.js:4:61)
    at Decoder._decode_dataset (/home/hayashis/git/dicom/node_modules/dicom/lib/decoder.js:168:14)
    at Decoder.<anonymous> (/home/hayashis/git/dicom/node_modules/dicom/lib/decoder.js:4:61)
    at Decoder._decode_metainfo (/home/hayashis/git/dicom/node_modules/dicom/lib/decoder.js:163:19)
    at Decoder._decode_metainfo (/home/hayashis/git/dicom/node_modules/dicom/lib/decoder.js:4:61)

I don't know much about DICOM dictionary to know if this is a bug, or just a known limitation with node-dicom. If it is, is there a work around (maybe just parse other header and ignore this VR?

Thank you!

**Comment by grmble** [comment]
I am horribly late, but thank you :)
