### ISSUE TITLE
how to deal with the err?

### ISSUE THREAD

**Issue by KingMario** [grmble/node-dicom#9]
dear grmble,

I'm using your great library to deal with files. Some of the files are not dicom formatted, so I use the following try ... catch block, but I find that the error thrown by the library is not caught and my app just collapse with the `Unhandled 'error' event`.

Could you please tell me how to handle the error thrown here. Thanks.

    try {
        fs.createReadStream(fileName).pipe(decoder).pipe(encoder).pipe(sink);
    } catch (err) {
        console.log(err);
        fileHandled++;
    }

err info:
{"name":"decoder","hostname":"marioMacBook-Air.local","pid":1465,"level":50,"error":{},"msg":"_action_wrapper:  emitting error","time":"2015-07-14T06:30:07.222Z","v":0}
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Unable to guess DICOM encoding
    at DicomError.Error (native)
    at new DicomError (/Users/Mario/work/sysyunshung/ufop/New Spec/zufop/node_modules/dicom/lib/vrs.js:17:47)
    at Decoder._guess_header (/Users/Mario/work/sysyunshung/ufop/New Spec/zufop/node_modules/dicom/lib/decoder.js:250:13)
    at /Users/Mario/work/sysyunshung/ufop/New Spec/zufop/node_modules/dicom/lib/decoder.js:4:61
    at Decoder._action_wrapper (/Users/Mario/work/sysyunshung/ufop/New Spec/zufop/node_modules/dicom/lib/decoder.js:205:16)
    at Decoder._transform (/Users/Mario/work/sysyunshung/ufop/New Spec/zufop/node_modules/dicom/lib/decoder.js:80:12)
    at Decoder.Transform._read (_stream_transform.js:179:10)
    at Decoder.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)

**Comment by KingMario** [comment]
By studying the nodejs documents, I learned that I should have used the domain.on(‘error’, cb) instead of using the try ... catch ...

Issue closed.
